apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ipfs-cluster-rpc
spec:
  backend:
    serviceName: ipfs-api
    servicePort: 9095
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: ipfs-rpc-certificate
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ipfs-rpc-backendconfig
