apiVersion: v1
kind: Service
metadata:
  name: ipfs-p2p
  labels:
    app: ipfs-cluster
spec:
  type: LoadBalancer
  ports:
    - name: ipfs-swarm
      targetPort: ipfs-swarm
      port: 4001
  selector:
    app: ipfs-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-api
  labels:
    app: ipfs-cluster
spec:
  type: NodePort
  ports:
    - name: cluster-api
      targetPort: cluster-api
      port: 9094
  selector:
    app: ipfs-cluster
